apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-sub
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rabbitmq-sub
  template:
    metadata:
      labels:
        app: rabbitmq-sub
    spec:
      containers:
        - name: rabbitmq-sub
          image: arsenikki/rabbitmq-sub:v2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: hostName
              value: "my-rabbit"
            - name: port
              value: "5672"
            - name: queueName
              value: "task-queue"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-sub
spec:
  selector:
    app: rabbitmq-sub
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-sub
  labels:
    name: rabbitmq-sub
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: rabbitmq-sub
                port:
                  number: 80
